- id: tf-fmt
  name: terraform fmt
  description: Run terraform fmt
  require_serial: true
  entry: terraform-py fmt
  language: python
  types: [terraform]

- id: tf-validate
  name: terraform validate
  description: Run terraform validate
  require_serial: true
  entry: terraform-py validate
  language: python
  types: [terraform]

- id: tf-providers-lock
  name: terraform providers lock
  description: Run terraform providers lock
  require_serial: true
  pass_filenames: false
  entry: terraform-py providers_lock
  args: [./]
  language: python
  types: [terraform]
